apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  template:
    spec:
      containers:
        - name: identity-service
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/identity-service:48c85a52f22319f47656305ed82e0123e7eddffe
          imagePullPolicy: Always
