apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: ai-service-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: ai-service-secret

  dataFrom:
    - extract:
        key: ai-service/prod