apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ai-service-secret
  data:
    - secretKey: LLM_API_KEY
      remoteRef:
        key: groq-api-key
        property: LLM_API_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: ai-db
        property: DATABASE_URL
