apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: api-gateway-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: api-gateway-secret

  dataFrom:
    - extract:
        key: api-gateway/prod