apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: identity-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: identity-service-secret
  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: jwt-secret
        property: JWT_SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: identity-db
        property: DATABASE_URL
