apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: identity-service-secret
  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: dev-jwt-secret
        property: JWT_SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: dev-identity-db
        property: DATABASE_URL
