apiVersion: external-secrets.io/v1beta1
kind: SecretStore

metadata:
  name: aws-secretsmanager

spec:
  provider:
    aws:
      service: SecretsManager 
      region: ap-southeast-1 # Change to your real AWS region

      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets