apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services

resources:
  - ../../manifests/base

images:
  - name: aimatch-identity-service
    newName: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/identity-service
    newTag: latest
  - name: aimatch-recruitment-service
    newName: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/recruitment-service
    newTag: latest
  - name: aimatch-ai-service
    newName: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/ai-service
    newTag: latest
  - name: aimatch-api-gateway
    newName: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/api-gateway
    newTag: latest

patches:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: identity-service
    spec:
      template:
        spec:
          containers:
          - name: identity-service
            imagePullPolicy: Always
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: recruitment-service
    spec:
      template:
        spec:
          containers:
          - name: recruitment-service
            imagePullPolicy: Always
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ai-service
    spec:
      template:
        spec:
          containers:
          - name: ai-service
            imagePullPolicy: Always
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-gateway
    spec:
      template:
        spec:
          containers:
          - name: api-gateway
            imagePullPolicy: Always

replicas:
  - name: identity-service
    count: 2
  - name: recruitment-service
    count: 2
  - name: ai-service
    count: 2
  - name: api-gateway
    count: 2
