apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:3150b8d8362622d868038d12e256717f5ef78471
          imagePullPolicy: Always
