apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:0167f057a0dff3200ba5e51168e417a210999c2b
          imagePullPolicy: Always
