apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  template:
    spec:
      containers:
        - name: identity-service
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/identity-service:4456343fe9b852f1d87b85918d402da3d4439d7b
          imagePullPolicy: Always
