apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  template:
    spec:
      containers:
        - name: identity-service
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/identity-service:80c947c2f39cfe951621ee71c0cbff5c971c8349
          imagePullPolicy: Always
