apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  template:
    spec:
      containers:
        - name: ai-service
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/ai-service:bcb199662302843f7d3dda9d23bf213d481d9a21
          imagePullPolicy: Always
