apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-service
spec:
  template:
    spec:
      containers:
        - name: recruitment-service
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/recruitment-service:4d8b832d3b4faec360db09c8f347df6ee788f7fb
          imagePullPolicy: Always
