apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          image: 832388983718.dkr.ecr.ap-southeast-1.amazonaws.com/api-gateway:38eb68b9945c9c45b2e2a63ac8abfab5b56ae7ff
          imagePullPolicy: Always
