apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  
  - configmaps/identity-service-configmap.yaml
  - configmaps/recruitment-service-configmap.yaml
  - configmaps/ai-service-configmap.yaml
  - configmaps/api-gateway-configmap.yaml
  # - secrets/identity-service/
  # - secrets/recruitment-service/
  # - secrets/ai-service/
  # - secrets/api-gateway/
  - external-secrets/secret-store.yaml
  - external-secrets/identity-service-secret.yaml
  - external-secrets/recruitment-service-secret.yaml
  - external-secrets/ai-service-secret.yaml
  - external-secrets/api-gateway-secret.yaml

  - deployments/identity-service-deployment.yaml
  - deployments/recruitment-service-deployment.yaml
  - deployments/ai-service-deployment.yaml
  - deployments/api-gateway-deployment.yaml

  - services/identity-service.yaml
  - services/recruitment-service.yaml
  - services/ai-service.yaml
  - services/api-gateway.yaml

namespace: aimatch