name: API Gateway CI

on:
  push:
    branches:
      - main
      - stage
    paths:
      - "backend/services/api-gateway/**"
      - ".github/workflows/api-gateway-ci.yml"
      - ".github/workflows/template-backend.yaml"

  pull_request:
    branches:
      - main
      - stage
    paths:
      - "backend/services/api-gateway/**"
      - ".github/workflows/api-gateway-ci.yml"
      - ".github/workflows/template-backend.yaml"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-rules:
    uses: ./.github/workflows/enforce-rule-branch.yaml
    secrets: inherit
  api-gateway-ci:
    uses: ./.github/workflows/template-backend.yaml
    secrets: inherit
    needs: check-rules
    with:
      service_path: backend/services/api-gateway
      image_name: api-gateway
      image_tag: ${{ github.event.pull_request.head.sha || github.sha }}
      cache_dependency_glob: backend/services/api-gateway/pyproject.toml
      aws_region: ap-southeast-1
      aws_account_id: "832388983718"
      jwt_secret_key: test-secret
      jwt_algorithm: HS256
      identity_service_url: http://identity-service:8001
      recruitment_service_url: http://recruitment-service:8002
      ai_service_url: http://ai-service:8003
