name: Identity Service CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/services/identity-service/**"
      - ".github/workflows/identity-service-ci.yml"

  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/services/identity-service/**"
      - ".github/workflows/identity-service-ci.yml"
      - ".github/workflows/template-backend.yaml"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  identity-service-ci:
    uses: ./.github/workflows/template-backend.yaml
    secrets: inherit
    with:
      service_path: backend/services/identity-service
      image_name: identity-service
      image_tag: ${{ github.event.pull_request.head.sha || github.sha }}
      cache_dependency_glob: backend/services/identity-service/uv.lock
      aws_region: ap-southeast-1
      aws_account_id: "832388983718"
      database_url: postgresql+psycopg://postgres:postgres@localhost:5433/aimatch_test_db
      jwt_secret_key: test-secret
      postgres_port: "5433"
