name: Recruitment Service CI

on:
  push:
    branches:
      - main
      - stage
    paths:
      - "backend/services/recruitment-service/**"
      - ".github/workflows/recruitment-service-ci.yml"
      - ".github/workflows/template-backend.yaml"

  pull_request:
    branches:
      - main
      - stage
    paths:
      - "backend/services/recruitment-service/**"
      - ".github/workflows/recruitment-service-ci.yml"
      - ".github/workflows/template-backend.yaml"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-rules:
    uses: ./.github/workflows/enforce-rule-branch.yaml
    secrets: inherit
  recruitment-service-ci:
    uses: ./.github/workflows/template-backend.yaml
    secrets: inherit
    needs: check-rules
    with:
      service_path: backend/services/recruitment-service
      image_name: recruitment-service
      image_tag: ${{ github.event.pull_request.head.sha || github.sha }}
      cache_dependency_glob: backend/services/recruitment-service/pyproject.toml
      aws_region: ap-southeast-1
      aws_account_id: "832388983718"
      database_url: postgresql+psycopg://postgres:postgres@localhost:5432/aimatch_test_db
